baseurl = "https://blog.theobrigitte.com/"
title = "Theo's Log"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
copyright = "© Copyright notice"

[markup.goldmark.renderer]
unsafe = true

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Théo Brigitte"
  description = "Théo Brigitte's personal log"
  keywords = "blog,developer,personal"
  gravatar = "theo.brigitte@gmail.com"

  faviconSVG = "/favicon.ico"

  since = 2012

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  url = "https://github.com/TheoBrigitte"
  weight = 1

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  url = "https://www.linkedin.com/in/th%C3%A9o-brigitte-a4326175/"
  weight = 2

[[params.social]]
  name = "CV"
  icon = "fa-solid fa-file-code fa-2x"
  url = "https://theobrigitte.com/cv.pdf"
  weight = 3

# menu links
[[menu.main]]
  name = "home"
  weight = 1
  url = "/"
[[menu.main]]
  name = "posts"
  weight = 2
  url = "posts/"
