baseurl = "https://blog.theobrigitte.com/"
title = "Theo's blog"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
copyright = "© Copyright notice"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Théo Brigitte"
  info = "A developer and tech enthusiast sharing knowledge and experiences."
  description = "Théo Brigitte's personal website"
  keywords = "blog,developer,personal"
  gravatar = "theo.brigitte@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2012

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  url = "https://github.com/TheoBrigitte"
  weight = 1

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
